package fingerprint

import (
	"regexp"

	"scanner/common"
)

// RuleData 指纹识别规则数据
type RuleData struct {
	Name     string
	Type     string
	Rule     string
	Compiled *regexp.Regexp // 预编译的正则表达式
}

// init 在程序启动时预编译所有正则表达式
func init() {
	for i := range RuleDatas {
		re, err := regexp.Compile(RuleDatas[i].Rule)
		if err != nil {
			common.LogDebug("fingerprint rule compile failed: " + RuleDatas[i].Name + " - " + err.Error())
			continue
		}
		RuleDatas[i].Compiled = re
	}
}

// Md5Data MD5指纹数据
type Md5Data struct {
	Name   string
	Md5Str string
}

// PocData POC漏洞检测数据
type PocData struct {
	Name  string
	Alias string
}

// RuleDatas 指纹识别规则数据集
var RuleDatas = []RuleData{
	{Name: "宝塔", Type: "code", Rule: "(app.bt.cn/static/app.png|安全入口校验失败|<title>入口校验失败</title>|href=\"http://www.bt.cn/bbs)"},
	{Name: "深信服防火墙类产品", Type: "code", Rule: "(SANGFOR FW)"},
	{Name: "360网站卫士", Type: "code", Rule: "(webscan.360.cn/status/pai/hash|wzws-waf-cgi|zhuji.360.cn/guard/firewall/stopattack.html)"},
	{Name: "360网站卫士", Type: "headers", Rule: "(360wzws|CWAP-waf|zhuji.360.cn|X-Safe-Firewall)"},
	{Name: "绿盟防火墙", Type: "code", Rule: "(NSFOCUS NF)"},
	{Name: "绿盟防火墙", Type: "headers", Rule: "(NSFocus)"},
	{Name: "Topsec-Waf", Type: "index", Rule: `(<META NAME="Copyright" CONTENT="Topsec Network Security Technology Co.,Ltd"/>","<META NAME="DESCRIPTION" CONTENT="Topsec web UI"/>)`},
	{Name: "Anquanbao", Type: "headers", Rule: "(Anquanbao)"},
	{Name: "BaiduYunjiasu", Type: "headers", Rule: "(yunjiasu)"},
	{Name: "BigIP", Type: "headers", Rule: "(BigIP|BIGipServer)"},
	{Name: "BinarySEC", Type: "headers", Rule: "(binarysec)"},
	{Name: "BlockDoS", Type: "headers", Rule: "(BlockDos.net)"},
	{Name: "CloudFlare", Type: "headers", Rule: "(cloudflare)"},
	{Name: "Cloudfront", Type: "headers", Rule: "(cloudfront)"},
	{Name: "Comodo", Type: "headers", Rule: "(Protected by COMODO)"},
	{Name: "IBM-DataPower", Type: "headers", Rule: "(X-Backside-Transport)"},
	{Name: "DenyAll", Type: "headers", Rule: "(sessioncookie=)"},
	{Name: "dotDefender", Type: "headers", Rule: "(dotDefender)"},
	{Name: "Incapsula", Type: "headers", Rule: "(X-CDN|Incapsula)"},
	{Name: "Jiasule", Type: "headers", Rule: "(jsluid=)"},
	{Name: "KONA", Type: "headers", Rule: "(AkamaiGHost)"},
	{Name: "ModSecurity", Type: "headers", Rule: "(Mod_Security|NOYB)"},
	{Name: "NetContinuum", Type: "headers", Rule: "(Cneonction|nnCoection|citrix_ns_id)"},
	{Name: "Newdefend", Type: "headers", Rule: "(newdefend)"},
	{Name: "Safe3", Type: "headers", Rule: "(Safe3WAF|Safe3 Web Firewall)"},
	{Name: "Safedog", Type: "code", Rule: "(404.safedog.cn/images/safedogsite/broswer_logo.jpg)"},
	{Name: "Safedog", Type: "headers", Rule: "(Safedog|WAF/2.0)"},
	{Name: "SonicWALL", Type: "headers", Rule: "(SonicWALL)"},
	{Name: "Stingray", Type: "headers", Rule: "(X-Mapping-)"},
	{Name: "Sucuri", Type: "headers", Rule: "(Sucuri/Cloudproxy)"},
	{Name: "Usp-Sec", Type: "headers", Rule: "(Secure Entry Server)"},
	{Name: "Varnish", Type: "headers", Rule: "(varnish)"},
	{Name: "Wallarm", Type: "headers", Rule: "(wallarm)"},
	{Name: "阿里云", Type: "code", Rule: "(errors.aliyun.com)"},
	{Name: "WebKnight", Type: "headers", Rule: "(WebKnight)"},
	{Name: "Yundun", Type: "headers", Rule: "(YUNDUN)"},
	{Name: "Yunsuo", Type: "headers", Rule: "(yunsuo)"},
	{Name: "Coding pages", Type: "header", Rule: "(Coding Pages)"},
	{Name: "启明防火墙", Type: "code", Rule: "(/cgi-bin/webui?op=get_product_model)"},
	{Name: "Shiro", Type: "headers", Rule: "(=deleteMe|rememberMe=)"},
	{Name: "Portainer(Docker管理)", Type: "code", Rule: "(portainer.updatePassword|portainer.init.admin)"},
	{Name: "Gogs简易Git服务", Type: "cookie", Rule: "(i_like_gogs)"},
	{Name: "Gitea简易Git服务", Type: "cookie", Rule: "(i_like_gitea)"},
	{Name: "Nexus", Type: "code", Rule: "(Nexus Repository Manager)"},
	{Name: "Nexus", Type: "cookie", Rule: "(NX-ANTI-CSRF-TOKEN)"},
	{Name: "Harbor", Type: "code", Rule: "(<title>Harbor</title>)"},
	{Name: "Harbor", Type: "cookie", Rule: "(harbor-lang)"},
	{Name: "禅道", Type: "code", Rule: "(/theme/default/images/main/zt-logo.png|/zentao/theme/zui/css/min.css)"},
	{Name: "禅道", Type: "cookie", Rule: "(zentaosid)"},
	{Name: "协众OA", Type: "code", Rule: "(Powered by 协众OA)"},
	{Name: "协众OA", Type: "cookie", Rule: "(CNOAOASESSID)"},
	{Name: "xxl-job", Type: "code", Rule: "(分布式任务调度平台XXL-JOB)"},
	{Name: "atmail-WebMail", Type: "cookie", Rule: "(atmail6)"},
	{Name: "atmail-WebMail", Type: "code", Rule: "(/index.php/mail/auth/processlogin|Powered by Atmail)"},
	{Name: "weblogic", Type: "code", Rule: "(/console/framework/skins/wlsconsole/images/login_WebLogic_branding.png|Welcome to Weblogic Application Server|<i>Hypertext Transfer Protocol -- HTTP/1.1</i>)"},
	{Name: "致远OA", Type: "code", Rule: "(/seeyon/common/|/seeyon/USER-DATA/IMAGES/LOGIN/login.gif)"},
	{Name: "discuz", Type: "code", Rule: "(content=\"Discuz! X\")"},
	{Name: "Typecho", Type: "code", Rule: "(Typecho</a>)"},
	{Name: "金蝶EAS", Type: "code", Rule: "(easSessionId)"},
	{Name: "phpMyAdmin", Type: "cookie", Rule: "(pma_lang|phpMyAdmin)"},
	{Name: "phpMyAdmin", Type: "code", Rule: "(/themes/pmahomme/img/logo_right.png)"},
	{Name: "H3C-AM8000", Type: "code", Rule: "(AM8000)"},
	{Name: "360企业版", Type: "code", Rule: "(360EntWebAdminMD5Secret)"},
	{Name: "H3C公司产品", Type: "code", Rule: "(service@h3c.com)"},
	{Name: "H3C ICG 1000", Type: "code", Rule: "(ICG 1000系统管理)"},
	{Name: "Citrix-Metaframe", Type: "code", Rule: "(window.location=\"/Citrix/MetaFrame)"},
	{Name: "H3C ER5100", Type: "code", Rule: "(ER5100系统管理)"},
	{Name: "阿里云CDN", Type: "code", Rule: "(cdn.aliyuncs.com)"},
	{Name: "CISCO_EPC3925", Type: "code", Rule: "(Docsis_system)"},
	{Name: "CISCO ASR", Type: "code", Rule: "(CISCO ASR)"},
	{Name: "H3C ER3200", Type: "code", Rule: "(ER3200系统管理)"},
	{Name: "万户oa", Type: "code", Rule: "(/defaultroot/templates/template_system/common/css/|/defaultroot/scripts/|css/css_whir.css)"},
	{Name: "Spark_Master", Type: "code", Rule: "(Spark Master at)"},
	{Name: "华为_HUAWEI_SRG2220", Type: "code", Rule: "(HUAWEI SRG2220)"},
	{Name: "蓝凌OA", Type: "code", Rule: "(/scripts/jquery.landray.common.js)"},
	{Name: "深信服ssl-vpn", Type: "code", Rule: "(login_psw.csp)"},
	{Name: "华为 NetOpen", Type: "code", Rule: "(/netopen/theme/css/inFrame.css)"},
	{Name: "Citrix-Web-PN-Server", Type: "code", Rule: "(Citrix Web PN Server)"},
	{Name: "juniper_vpn", Type: "code", Rule: "(welcome.cgi?p=logo|/images/logo_juniper_reversed.gif)"},
	{Name: "360主机卫士", Type: "headers", Rule: "(zhuji.360.cn)"},
	{Name: "Nagios", Type: "headers", Rule: "(Nagios Access)"},
	{Name: "H3C ER8300", Type: "code", Rule: "(ER8300系统管理)"},
	{Name: "Citrix-Access-Gateway", Type: "code", Rule: "(Citrix Access Gateway)"},
	{Name: "华为 MCU", Type: "code", Rule: "(McuR5-min.js)"},
	{Name: "TP-LINK Wireless WDR3600", Type: "code", Rule: "(TP-LINK Wireless WDR3600)"},
	{Name: "泛微OA", Type: "headers", Rule: "(ecology_JSessionid)"},
	{Name: "泛微OA", Type: "code", Rule: "(/spa/portal/public/index.js)"},
	{Name: "华为_HUAWEI_ASG2050", Type: "code", Rule: "(HUAWEI ASG2050)"},
	{Name: "360网站卫士", Type: "code", Rule: "(360wzb)"},
	{Name: "Citrix-XenServer", Type: "code", Rule: "(Citrix Systems, Inc. XenServer)"},
	{Name: "H3C ER2100V2", Type: "code", Rule: "(ER2100V2系统管理)"},
	{Name: "zabbix", Type: "cookie", Rule: "(zbx_sessionid)"},
	{Name: "zabbix", Type: "code", Rule: "(images/general/zabbix.ico|Zabbix SIA|zabbix-server: Zabbix)"},
	{Name: "CISCO_VPN", Type: "headers", Rule: "(webvpn)"},
	{Name: "360站长平台", Type: "code", Rule: "(360-site-verification)"},
	{Name: "H3C ER3108GW", Type: "code", Rule: "(ER3108GW系统管理)"},
	{Name: "o2security_vpn", Type: "headers", Rule: "(client_param=install_active)"},
	{Name: "H3C ER3260G2", Type: "code", Rule: "(ER3260G2系统管理)"},
	{Name: "H3C ICG1000", Type: "code", Rule: "(ICG1000系统管理)"},
	{Name: "CISCO-CX20", Type: "code", Rule: "(CISCO-CX20)"},
	{Name: "H3C ER5200", Type: "code", Rule: "(ER5200系统管理)"},
	{Name: "linksys-vpn-bragap14-parintins", Type: "code", Rule: "(linksys-vpn-bragap14-parintins)"},
	{Name: "360网站卫士常用前端公共库", Type: "code", Rule: "(libs.useso.com)"},
	{Name: "H3C ER3100", Type: "code", Rule: "(ER3100系统管理)"},
	{Name: "H3C-SecBlade-FireWall", Type: "code", Rule: "(js/MulPlatAPI.js)"},
	{Name: "360webfacil_360WebManager", Type: "code", Rule: "(publico/template/)"},
	{Name: "Citrix_Netscaler", Type: "code", Rule: "(ns_af)"},
	{Name: "H3C ER6300G2", Type: "code", Rule: "(ER6300G2系统管理)"},
	{Name: "H3C ER3260", Type: "code", Rule: "(ER3260系统管理)"},
	{Name: "华为_HUAWEI_SRG3250", Type: "code", Rule: "(HUAWEI SRG3250)"},
	{Name: "exchange", Type: "code", Rule: "(/owa/auth.owa|Exchange Admin Center)"},
	{Name: "Spark_Worker", Type: "code", Rule: "(Spark Worker at)"},
	{Name: "H3C ER3108G", Type: "code", Rule: "(ER3108G系统管理)"},
	{Name: "Citrix-ConfProxy", Type: "code", Rule: "(confproxy)"},
	{Name: "360网站安全检测", Type: "code", Rule: "(webscan.360.cn/status/pai/hash)"},
	{Name: "H3C ER5200G2", Type: "code", Rule: "(ER5200G2系统管理)"},
	{Name: "华为（HUAWEI）安全设备", Type: "code", Rule: "(sweb-lib/resource/)"},
	{Name: "华为（HUAWEI）USG", Type: "code", Rule: "(UI_component/commonDefine/UI_regex_define.js)"},
	{Name: "H3C ER6300", Type: "code", Rule: "(ER6300系统管理)"},
	{Name: "华为_HUAWEI_ASG2100", Type: "code", Rule: "(HUAWEI ASG2100)"},
	{Name: "TP-Link 3600 DD-WRT", Type: "code", Rule: "(TP-Link 3600 DD-WRT)"},
	{Name: "NETGEAR WNDR3600", Type: "code", Rule: "(NETGEAR WNDR3600)"},
	{Name: "H3C ER2100", Type: "code", Rule: "(ER2100系统管理)"},
	{Name: "jira", Type: "code", Rule: "(jira.webresources)"},
	{Name: "金和协同管理平台", Type: "code", Rule: "(金和协同管理平台)"},
	{Name: "Citrix-NetScaler", Type: "code", Rule: "(NS-CACHE)"},
	{Name: "linksys-vpn", Type: "headers", Rule: "(linksys-vpn)"},
	{Name: "通达OA", Type: "code", Rule: "(/static/images/tongda.ico|http://www.tongda2000.com|通达OA移动版|Office Anywhere)"},
	{Name: "华为（HUAWEI）Secoway设备", Type: "code", Rule: "(Secoway)"},
	{Name: "华为_HUAWEI_SRG1220", Type: "code", Rule: "(HUAWEI SRG1220)"},
	{Name: "H3C ER2100n", Type: "code", Rule: "(ER2100n系统管理)"},
	{Name: "H3C ER8300G2", Type: "code", Rule: "(ER8300G2系统管理)"},
	{Name: "金蝶政务GSiS", Type: "code", Rule: "(/kdgs/script/kdgs.js)"},
	{Name: "Jboss", Type: "code", Rule: "(Welcome to JBoss|jboss.css)"},
	{Name: "Jboss", Type: "headers", Rule: "(JBoss)"},
	{Name: "泛微E-mobile", Type: "code", Rule: "(Weaver E-mobile|weaver,e-mobile)"},
	{Name: "泛微E-mobile", Type: "headers", Rule: "(EMobileServer)"},
	{Name: "齐治堡垒机", Type: "code", Rule: "(logo-icon-ico72.png|resources/themes/images/logo-login.png)"},
	{Name: "ThinkPHP", Type: "headers", Rule: "(ThinkPHP)"},
	{Name: "ThinkPHP", Type: "code", Rule: "(/Public/static/js/)"},
	{Name: "weaver-ebridge", Type: "code", Rule: "(e-Bridge,http://wx.weaver)"},
	{Name: "Laravel", Type: "headers", Rule: "(laravel_session)"},
	{Name: "DWR", Type: "code", Rule: "(dwr/engine.js)"},
	{Name: "swagger_ui", Type: "code", Rule: "(swagger-ui/css|\"swagger\":|swagger-ui.min.js)"},
	{Name: "大汉版通发布系统", Type: "code", Rule: "(大汉版通发布系统|大汉网络)"},
	{Name: "druid", Type: "code", Rule: "(druid.index|DruidDrivers|DruidVersion|Druid Stat Index)"},
	{Name: "Jenkins", Type: "code", Rule: "(Jenkins)"},
	{Name: "红帆OA", Type: "code", Rule: "(iOffice)"},
	{Name: "VMware vSphere", Type: "code", Rule: "(VMware vSphere)"},
	{Name: "打印机", Type: "code", Rule: "(打印机|media/canon.gif)"},
	{Name: "finereport", Type: "code", Rule: "(isSupportForgetPwd|FineReport,Web Reporting Tool)"},
	{Name: "蓝凌OA", Type: "code", Rule: "(蓝凌软件|StylePath:\"/resource/style/default/\"|/resource/customization|sys/ui/extend/theme/default/style/profile.css|sys/ui/extend/theme/default/style/icon.css)"},
	{Name: "GitLab", Type: "code", Rule: "(href=\"https://about.gitlab.com/)"},
	{Name: "Jquery-1.7.2", Type: "code", Rule: "(/webui/js/jquerylib/jquery-1.7.2.min.js)"},
	{Name: "Hadoop Applications", Type: "code", Rule: "(/cluster/app/application)"},
	{Name: "海昌OA", Type: "code", Rule: "(/loginmain4/js/jquery.min.js)"},
	{Name: "帆软报表", Type: "code", Rule: "(WebReport/login.html|ReportServer)"},
	{Name: "帆软报表", Type: "headers", Rule: "(数据决策系统)"},
	{Name: "华夏ERP", Type: "headers", Rule: "(华夏ERP)"},
	{Name: "金和OA", Type: "cookie", Rule: "(ASPSESSIONIDSSCDTDBS)"},
	{Name: "久其财务报表", Type: "code", Rule: "(netrep/login.jsp|/netrep/intf)"},
	{Name: "若依管理系统", Type: "code", Rule: "(ruoyi/login.js|ruoyi/js/ry-ui.js)"},
	{Name: "启莱OA", Type: "code", Rule: "(js/jQselect.js|js/jquery-1.4.2.min.js)"},
	{Name: "智慧校园管理系统", Type: "code", Rule: "(DC_Login/QYSignUp)"},
	{Name: "JQuery-1.7.2", Type: "code", Rule: "(webui/js/jquerylib/jquery-1.7.2.min.js)"},
	{Name: "浪潮 ClusterEngineV4.0", Type: "code", Rule: "(0;url=module/login/login.html)"},
	{Name: "会捷通云视讯平台", Type: "code", Rule: "(him/api/rest/v1.0/node/role|him.app)"},
	{Name: "源码泄露账号密码 F12查看", Type: "code", Rule: "(get_dkey_passwd)"},
	{Name: "Smartbi Insight", Type: "code", Rule: "(smartbi.gcf.gcfutil)"},
	{Name: "汉王人脸考勤管理系统", Type: "code", Rule: "(汉王人脸考勤管理系统|/Content/image/hanvan.png|/Content/image/hvicon.ico)"},
	{Name: "亿赛通-电子文档安全管理系统", Type: "code", Rule: "(电子文档安全管理系统|/CDGServer3/index.jsp|/CDGServer3/SysConfig.jsp|/CDGServer3/help/getEditionInfo.jsp)"},
	{Name: "天融信 TopApp-LB 负载均衡系统", Type: "code", Rule: "(TopApp-LB 负载均衡系统)"},
	{Name: "中新金盾信息安全管理系统", Type: "code", Rule: "(中新金盾信息安全管理系统|中新网络信息安全股份有限公司)"},
	{Name: "好视通", Type: "code", Rule: "(深圳银澎云计算有限公司|itunes.apple.com/us/app/id549407870|hao-shi-tong-yun-hui-yi-yuan)"},
	{Name: "蓝海卓越计费管理系统", Type: "code", Rule: "(蓝海卓越计费管理系统|星锐蓝海网络科技有限公司)"},
	{Name: "和信创天云桌面系统", Type: "code", Rule: "(和信下一代云桌面VENGD|/vesystem/index.php)"},
	{Name: "金山", Type: "code", Rule: "(北京猎鹰安全科技有限公司|金山终端安全系统V9.0Web控制台|北京金山安全管理系统技术有限公司|金山V8)"},
	{Name: "WIFISKY-7层流控路由器", Type: "code", Rule: "(深圳市领空技术有限公司|WIFISKY 7层流控路由器)"},
	{Name: "MetInfo-米拓建站", Type: "code", Rule: "(MetInfo|/skin/style/metinfo.css|/skin/style/metinfo-v2.css)"},
	{Name: "IBM-Lotus-Domino", Type: "code", Rule: "(/mailjump.nsf|/domcfg.nsf|/names.nsf|/homepage.nsf)"},
	{Name: "APACHE-kylin", Type: "code", Rule: "(url=kylin)"},
	{Name: "C-Lodop打印服务系统", Type: "code", Rule: "(/CLodopfuncs.js|www.c-lodop.com)"},
	{Name: "HFS", Type: "code", Rule: "(href=\"http://www.rejetto.com/hfs/)"},
	{Name: "Jellyfin", Type: "code", Rule: "(content=\"http://jellyfin.org\")"},
	{Name: "FIT2CLOUD-JumpServer-堡垒机", Type: "code", Rule: "(<title>JumpServer</title>)"},
	{Name: "Alibaba Nacos", Type: "code", Rule: "(<title>Nacos</title>)"},
	{Name: "Nagios", Type: "headers", Rule: "(nagios admin)"},
	{Name: "Pulse Connect Secure", Type: "code", Rule: "(/dana-na/imgs/space.gif)"},
	{Name: "h5ai", Type: "code", Rule: "(powered by h5ai)"},
	{Name: "jeesite", Type: "cookie", Rule: "(jeesite.session.id)"},
	{Name: "拓尔思SSO", Type: "cookie", Rule: "(trsidsssosessionid)"},
	{Name: "拓尔思WCMv7/6", Type: "cookie", Rule: "(com.trs.idm.coSessionId)"},
	{Name: "天融信脆弱性扫描与管理系统", Type: "code", Rule: "(/js/report/horizontalReportPanel.js)"},
	{Name: "天融信网络审计系统", Type: "code", Rule: "(onclick=dlg_download())"},
	{Name: "天融信日志收集与分析系统", Type: "code", Rule: "(天融信日志收集与分析系统)"},
	{Name: "URP教务系统", Type: "code", Rule: "(北京清元优软科技有限公司)"},
	{Name: "科来RAS", Type: "code", Rule: "(科来软件 版权所有|i18ninit.min.js)"},
	{Name: "正方OA", Type: "code", Rule: "(zfoausername)"},
	{Name: "希尔OA", Type: "code", Rule: "(/heeroa/login.do)"},
	{Name: "泛普建筑工程施工OA", Type: "code", Rule: "(/dwr/interface/LoginService.js)"},
	{Name: "中望OA", Type: "code", Rule: "(/IMAGES/default/first/xtoa_logo.png|/app_qjuserinfo/qjuserinfoadd.jsp)"},
	{Name: "海天OA", Type: "code", Rule: "(HTVOS.js)"},
	{Name: "信达OA", Type: "code", Rule: "(http://www.xdoa.cn</a>)"},
	{Name: "任我行CRM", Type: "code", Rule: "(CRM_LASTLOGINUSERKEY)"},
	{Name: "Spammark邮件信息安全网关", Type: "code", Rule: "(/cgi-bin/spammark?empty=1)"},
	{Name: "winwebmail", Type: "code", Rule: "(WinWebMail Server|images/owin.css)"},
	{Name: "浪潮政务系统", Type: "code", Rule: "(LangChao.ECGAP.OutPortal|OnlineQuery/QueryList.aspx)"},
	{Name: "天融信防火墙", Type: "code", Rule: "(/cgi/maincgi.cgi)"},
	{Name: "网神防火墙", Type: "code", Rule: "(css/lsec/login.css)"},
	{Name: "帕拉迪统一安全管理和综合审计系统", Type: "code", Rule: "(module/image/pldsec.css)"},
	{Name: "蓝盾BDWebGuard", Type: "code", Rule: "(BACKGROUND: url(images/loginbg.jpg) #e5f1fc)"},
	{Name: "Huawei SMC", Type: "code", Rule: "(Script/SmcScript.js?version=)"},
	{Name: "coremail", Type: "code", Rule: "(/coremail/bundle/|contextRoot: \"/coremail\"|coremail/common)"},
	{Name: "activemq", Type: "code", Rule: "(activemq_logo|Manage ActiveMQ broker)"},
	{Name: "锐捷网络", Type: "code", Rule: "(static/img/title.ico|support.ruijie.com.cn|Ruijie - NBR|eg.login.loginBtn)"},
	{Name: "禅道", Type: "code", Rule: "(/theme/default/images/main/zt-logo.png|zentaosid)"},
	{Name: "weblogic", Type: "code", Rule: "(/console/framework/skins/wlsconsole/images/login_WebLogic_branding.png|Welcome to Weblogic Application Server|<i>Hypertext Transfer Protocol -- HTTP/1.1</i>|<TITLE>Error 404--Not Found</TITLE>|Welcome to Weblogic Application Server|<title>Oracle WebLogic Server 管理控制台</title>)"},
	{Name: "weblogic", Type: "headers", Rule: "(WebLogic)"},
	{Name: "致远OA", Type: "code", Rule: "(/seeyon/USER-DATA/IMAGES/LOGIN/login.gif|/seeyon/common/)"},
	{Name: "蓝凌EIS智慧协同平台", Type: "code", Rule: "(/scripts/jquery.landray.common.js)"},
	{Name: "深信服ssl-vpn", Type: "code", Rule: "(login_psw.csp|loginPageSP/loginPrivacy.js|/por/login_psw.csp)"},
	{Name: "Struts2", Type: "code", Rule: "(org.apache.struts2|Struts Problem Report|struts.devMode|struts-tags|There is no Action mapped for namespace)"},
	{Name: "泛微OA", Type: "code", Rule: "(/spa/portal/public/index.js|wui/theme/ecology8/page/images/login/username_wev8.png|/wui/index.html#/?logintype=1)"},
	{Name: "Swagger UI", Type: "code", Rule: "(/swagger-ui.css|swagger-ui-bundle.js|swagger-ui-standalone-preset.js)"},
	{Name: "金蝶政务GSiS", Type: "code", Rule: "(/kdgs/script/kdgs.js|HTML5/content/themes/kdcss.min.css|/ClientBin/Kingdee.BOS.XPF.App.xap)"},
	{Name: "蓝凌OA", Type: "code", Rule: "(蓝凌软件|StylePath:\"/resource/style/default/\"|/resource/customization|sys/ui/extend/theme/default/style/icon.css|sys/ui/extend/theme/default/style/profile.css)"},
	{Name: "用友NC", Type: "code", Rule: "(Yonyou UAP|YONYOU NC|/Client/Uclient/UClient.dmg|logo/images/ufida_nc.png|iufo/web/css/menu.css|/System/Login/Login.asp?AppID=|/nc/servlet/nc.ui.iufo.login.Index)"},
	{Name: "用友IUFO", Type: "code", Rule: "(iufo/web/css/menu.css)"},
	{Name: "TELEPORT堡垒机", Type: "code", Rule: "(/static/plugins/blur/background-blur.js)"},
	{Name: "JEECMS", Type: "code", Rule: "(/r/cms/www/red/js/common.js|/r/cms/www/red/js/indexshow.js|Powered by JEECMS|JEECMS|/jeeadmin/jeecms/index.do)"},
	{Name: "CMS", Type: "code", Rule: "(Powered by .*CMS)"},
	{Name: "目录遍历", Type: "code", Rule: "(Directory listing for /)"},
	{Name: "ATLASSIAN-Confluence", Type: "code", Rule: "(com.atlassian.confluence)"},
	{Name: "ATLASSIAN-Confluence", Type: "headers", Rule: "(X-Confluence)"},
	{Name: "向日葵", Type: "code", Rule: "({\"success\":false,\"msg\":\"Verification failure\"})"},
	{Name: "Kubernetes", Type: "code", Rule: "(Kubernetes Dashboard</title>|Kubernetes Enterprise Manager|Mirantis Kubernetes Engine|Kubernetes Resource Report)"},
	{Name: "WordPress", Type: "code", Rule: "(/wp-login.php?action=lostpassword|WordPress</title>)"},
	{Name: "RabbitMQ", Type: "code", Rule: "(RabbitMQ Management)"},
	{Name: "dubbo", Type: "headers", Rule: "(Basic realm=\"dubbo\")"},
	{Name: "Spring env", Type: "code", Rule: "(logback)"},
	{Name: "ueditor", Type: "code", Rule: "(ueditor.all.js|UE.getEditor)"},
	{Name: "亿邮电子邮件系统", Type: "code", Rule: "(亿邮电子邮件系统|亿邮邮件整体解决方案)"},
}

// Md5Datas MD5指纹数据集
var Md5Datas = []Md5Data{
	{"BIG-IP", "04d9541338e525258daf47cc844d59f3"},
	{"蓝凌OA", "302464c3f6207d57240649926cfc7bd4"},
	{"JBOSS", "799f70b71314a7508326d1d2f68f7519"},
	{"锐捷网络", "d8d7c9138e93d43579ebf2e384745ba8"},
	{"锐捷网络", "9c21df9129aeec032df8ac15c84e050d"},
	{"锐捷网络", "a45883b12d753bc87aff5bddbef16ab3"},
	{"深信服edr", "0b24d4d5c7d300d50ee1cd96059a9e85"},
	{"致远OA", "cdc85452665e7708caed3009ecb7d4e2"},
	{"致远OA", "17ac348fcce0b320e7bfab3fe2858dfa"},
	{"致远OA", "57f307ad3764553df84e7b14b7a85432"},
	{"致远OA", "3c8df395ec2cbd72782286d18a286a9a"},
	{"致远OA", "2f761c27b6b7f9386bbd61403635dc42"},
	{"齐治堡垒机", "48ee373f098d8e96e53b7dd778f09ff4"},
	{"SpringBoot", "0488faca4c19046b94d07c3ee83cf9d6"},
	{"ThinkPHP", "f49c4a4bde1eec6c0b80c2277c76e3db"},
	{"通达OA", "ed0044587917c76d08573577c8b72883"},
	{"泛微E-mobile", "41eca7a9245394106a09b2534d8030df"},
	{"泛微OA", "c27547e27e1d2c7514545cd8d5988946"},
	{"泛微OA", "9b1d3f08ede38dbe699d6b2e72a8febb"},
	{"泛微OA", "281348dd57383c1f214ffb8aed3a1210"},
	{"GitLab", "85c754581e1d4b628be5b7712c042224"},
	{"Hikvision-视频监控", "89b932fcc47cf4ca3faadb0cfdef89cf"},
	{"华夏erp", "c68b15c45cf80115a943772f7d0028a6"},
	{"OpenSNS", "08711abfb016a55c0e84f7b54bef5632"},
	{"MetInfo-米拓建站", "2a9541b5c2225ed2f28734c0d75e456f"},
	{"IBM-Lotus-Domino", "36c1002bb579edf52a472b9d2e39bb50"},
	{"IBM-Lotus-Domino", "639b61409215d770a99667b446c80ea1"},
	{"ATLASSIAN-Confluence", "b91d19259cf480661ef93b67beb45234"},
	{"activemq", "05664fb0c7afcd6436179437e31f3aa6"},
	{"coremail", "ad74ff8f9a2f630fc2c5e6b3aa0a5cb8"},
}

// PocDatas POC漏洞检测数据集
var PocDatas = []PocData{
	{"致远OA", "seeyon"},
	{"泛微OA", "weaver"},
	{"通达OA", "tongda"},
	{"蓝凌OA", "landray"},
	{"ThinkPHP", "thinkphp"},
	{"Nexus", "nexus"},
	{"齐治堡垒机", "qizhi"},
	{"weaver-ebridge", "weaver-ebridge"},
	{"weblogic", "weblogic"},
	{"zabbix", "zabbix"},
	{"VMware vSphere", "vmware"},
	{"Jboss", "jboss"},
	{"用友", "yongyou"},
	{"用友IUFO", "yongyou"},
	{"coremail", "coremail"},
	{"金山", "kingsoft"},
}
